# Generated by Django 2.0.4 on 2018-06-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0005_auto_20180608_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='person',
        ),
    ]
