# Generated by Django 2.0.4 on 2018-07-17 16:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import medic.models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0006_auto_20180608_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(to='medic.ImageAttentionChannel')),
            ],
            options={
                'verbose_name_plural': 'Servicios a Domicilio',
                'verbose_name': 'Servicio a Domicilio',
            },
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
        migrations.AddField(
            model_name='chat',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personalDocumentFile',
            field=models.ImageField(blank=True, null=True, upload_to=medic.models.profileFilePath),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personalDocumentNumber',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Numero de documento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='professionalCardFile',
            field=models.ImageField(blank=True, null=True, upload_to=medic.models.profileFilePath),
        ),
        migrations.AlterField(
            model_name='profile',
            name='professionalCardNumber',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medic.Profile'),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='schedules',
            field=models.ManyToManyField(to='medic.ScheduleAttentionChannel'),
        ),
    ]
