# Generated by Django 2.0.4 on 2018-07-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0008_auto_20180717_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
    ]
