# Generated by Django 2.0.4 on 2018-07-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0009_auto_20180717_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypatology',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
