# Generated by Django 2.0.4 on 2018-08-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0012_auto_20180811_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='address_full',
            field=models.TextField(blank=True, null=True),
        ),
    ]
