# Generated by Django 2.0.4 on 2018-08-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0013_auto_20180811_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='patology',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
