# Generated by Django 2.0.4 on 2018-08-21 02:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0016_auto_20180821_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medic.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='address',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='city',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='created',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='images',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='position',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='schedules',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='homevisit',
            name='address',
        ),
        migrations.RemoveField(
            model_name='homevisit',
            name='city',
        ),
        migrations.RemoveField(
            model_name='homevisit',
            name='created',
        ),
        migrations.RemoveField(
            model_name='homevisit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homevisit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='homevisit',
            name='images',
        ),
        migrations.RemoveField(
            model_name='homevisit',
            name='position',
        ),
        migrations.RemoveField(
            model_name='homevisit',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='homevisit',
            name='schedules',
        ),
        migrations.RemoveField(
            model_name='homevisit',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='homevisit',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='office',
            name='address',
        ),
        migrations.RemoveField(
            model_name='office',
            name='city',
        ),
        migrations.RemoveField(
            model_name='office',
            name='created',
        ),
        migrations.RemoveField(
            model_name='office',
            name='description',
        ),
        migrations.RemoveField(
            model_name='office',
            name='id',
        ),
        migrations.RemoveField(
            model_name='office',
            name='images',
        ),
        migrations.RemoveField(
            model_name='office',
            name='position',
        ),
        migrations.RemoveField(
            model_name='office',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='office',
            name='schedules',
        ),
        migrations.RemoveField(
            model_name='office',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='office',
            name='updated',
        ),
        migrations.AddField(
            model_name='chat',
            name='attentionchannel_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medic.AttentionChannel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homevisit',
            name='attentionchannel_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medic.AttentionChannel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageattentionchannel',
            name='attention_channel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medic.AttentionChannel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='attentionchannel_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medic.AttentionChannel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleattentionchannel',
            name='attention_channel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medic.AttentionChannel'),
            preserve_default=False,
        ),
    ]
