# Generated by Django 2.0.4 on 2018-08-26 02:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0017_auto_20180826_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('attentionchannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medic.AttentionChannel')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
            bases=('medic.attentionchannel',),
        ),
        migrations.CreateModel(
            name='HomeVisit',
            fields=[
                ('attentionchannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medic.AttentionChannel')),
            ],
            options={
                'verbose_name': 'Servicio a Domicilio',
                'verbose_name_plural': 'Servicios a Domicilio',
            },
            bases=('medic.attentionchannel',),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('attentionchannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medic.AttentionChannel')),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
            },
            bases=('medic.attentionchannel',),
        ),
        migrations.AddField(
            model_name='attentionchannel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medic.Profile'),
        ),
    ]
