# Generated by Django 2.0.4 on 2018-04-29 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medic', '0004_auto_20180429_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestPQR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_request_user', models.TextField()),
                ('email_request_user', models.TextField()),
                ('phone_request_user', models.TextField()),
                ('description', models.TextField()),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medic.Profile')),
                ('request_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medic.RequestOrderMedicDate')),
            ],
            options={
                'verbose_name': 'Petición PQR',
                'verbose_name_plural': 'Peticiones PQR',
            },
        ),
    ]
