# Generated by Django 2.0.4 on 2018-06-08 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pqr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpqr',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medic.Profile'),
        ),
        migrations.AlterField(
            model_name='requestpqr',
            name='request_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medic.RequestOrderMedicDate'),
        ),
    ]
