version: 2
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: ls
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud --quiet compute copy-files ./dist instance-1:/tmp/ --zone $GCLOUD_INSTANCE_ZONE

workflows:
  version: 2
  deploy_backend:
    jobs:
      - deploy