# Generated by Django 2.0.4 on 2018-04-29 16:07

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import medic.models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0003_auto_20180209_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPatology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categorias de Patologías',
                'verbose_name': 'Categoria de Patologías',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Consultorios',
                'verbose_name': 'Consultorio',
            },
        ),
        migrations.CreateModel(
            name='ImageAttentionChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=medic.models.profileFilePath)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('images', models.ManyToManyField(to='medic.ImageAttentionChannel')),
            ],
            options={
                'verbose_name_plural': 'Consultorios',
                'verbose_name': 'Consultorio',
            },
        ),
        migrations.CreateModel(
            name='Patology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medic.CategoryPatology')),
            ],
            options={
                'verbose_name_plural': 'Patologías',
                'verbose_name': 'Patología',
            },
        ),
        migrations.CreateModel(
            name='ProfilePatologyOrCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medic.CategoryPatology')),
                ('patology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medic.Patology')),
            ],
            options={
                'verbose_name_plural': 'Patologías o categorías del perfil',
                'verbose_name': 'Patología o categoría del perfil',
            },
        ),
        migrations.CreateModel(
            name='RequestOrderMedicDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pacient', models.TextField()),
                ('age_pacient', models.IntegerField()),
                ('adicional_description_pacient', models.TextField()),
                ('email_pacient', models.TextField()),
                ('phone', models.TextField()),
                ('patology_pacient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medic.Patology')),
            ],
            options={
                'verbose_name_plural': 'Peticiones de cita medica',
                'verbose_name': 'Petición de cita medica',
            },
        ),
        migrations.CreateModel(
            name='ScheduleAttentionChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitDays', models.IntegerField()),
                ('duration', models.DurationField()),
            ],
            options={
                'verbose_name_plural': 'Horarios de canal de atención',
                'verbose_name': 'Horario de canal de atención',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 4, 29, 16, 7, 22, 40041, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default='POINT(0.0 0.0)', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 4, 29, 16, 7, 36, 413127, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studies',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilepatologyorcategory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medic.Profile'),
        ),
        migrations.AddField(
            model_name='office',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medic.Profile'),
        ),
        migrations.AddField(
            model_name='office',
            name='schedules',
            field=models.ManyToManyField(to='medic.ScheduleAttentionChannel'),
        ),
        migrations.AddField(
            model_name='chat',
            name='images',
            field=models.ManyToManyField(to='medic.ImageAttentionChannel'),
        ),
        migrations.AddField(
            model_name='chat',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medic.Profile'),
        ),
        migrations.AddField(
            model_name='chat',
            name='schedules',
            field=models.ManyToManyField(to='medic.ScheduleAttentionChannel'),
        ),
    ]
